// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class InvestPctUpdated extends ethereum.Event {
  get params(): InvestPctUpdated__Params {
    return new InvestPctUpdated__Params(this);
  }
}

export class InvestPctUpdated__Params {
  _event: InvestPctUpdated;

  constructor(event: InvestPctUpdated) {
    this._event = event;
  }

  get percentage(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }
}

export class LossTolerancePctUpdated extends ethereum.Event {
  get params(): LossTolerancePctUpdated__Params {
    return new LossTolerancePctUpdated__Params(this);
  }
}

export class LossTolerancePctUpdated__Params {
  _event: LossTolerancePctUpdated;

  constructor(event: LossTolerancePctUpdated) {
    this._event = event;
  }

  get pct(): i32 {
    return this._event.parameters[0].value.toI32();
  }
}

export class PerfFeePctUpdated extends ethereum.Event {
  get params(): PerfFeePctUpdated__Params {
    return new PerfFeePctUpdated__Params(this);
  }
}

export class PerfFeePctUpdated__Params {
  _event: PerfFeePctUpdated;

  constructor(event: PerfFeePctUpdated) {
    this._event = event;
  }

  get pct(): i32 {
    return this._event.parameters[0].value.toI32();
  }
}

export class StrategyUpdated extends ethereum.Event {
  get params(): StrategyUpdated__Params {
    return new StrategyUpdated__Params(this);
  }
}

export class StrategyUpdated__Params {
  _event: StrategyUpdated;

  constructor(event: StrategyUpdated) {
    this._event = event;
  }

  get strategy(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class TreasuryUpdated extends ethereum.Event {
  get params(): TreasuryUpdated__Params {
    return new TreasuryUpdated__Params(this);
  }
}

export class TreasuryUpdated__Params {
  _event: TreasuryUpdated;

  constructor(event: TreasuryUpdated) {
    this._event = event;
  }

  get treasury(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class IVaultSettings extends ethereum.SmartContract {
  static bind(address: Address): IVaultSettings {
    return new IVaultSettings("IVaultSettings", address);
  }
}

export class SetInvestPctCall extends ethereum.Call {
  get inputs(): SetInvestPctCall__Inputs {
    return new SetInvestPctCall__Inputs(this);
  }

  get outputs(): SetInvestPctCall__Outputs {
    return new SetInvestPctCall__Outputs(this);
  }
}

export class SetInvestPctCall__Inputs {
  _call: SetInvestPctCall;

  constructor(call: SetInvestPctCall) {
    this._call = call;
  }

  get _investPct(): i32 {
    return this._call.inputValues[0].value.toI32();
  }
}

export class SetInvestPctCall__Outputs {
  _call: SetInvestPctCall;

  constructor(call: SetInvestPctCall) {
    this._call = call;
  }
}

export class SetLossTolerancePctCall extends ethereum.Call {
  get inputs(): SetLossTolerancePctCall__Inputs {
    return new SetLossTolerancePctCall__Inputs(this);
  }

  get outputs(): SetLossTolerancePctCall__Outputs {
    return new SetLossTolerancePctCall__Outputs(this);
  }
}

export class SetLossTolerancePctCall__Inputs {
  _call: SetLossTolerancePctCall;

  constructor(call: SetLossTolerancePctCall) {
    this._call = call;
  }

  get _pct(): i32 {
    return this._call.inputValues[0].value.toI32();
  }
}

export class SetLossTolerancePctCall__Outputs {
  _call: SetLossTolerancePctCall;

  constructor(call: SetLossTolerancePctCall) {
    this._call = call;
  }
}

export class SetPerfFeePctCall extends ethereum.Call {
  get inputs(): SetPerfFeePctCall__Inputs {
    return new SetPerfFeePctCall__Inputs(this);
  }

  get outputs(): SetPerfFeePctCall__Outputs {
    return new SetPerfFeePctCall__Outputs(this);
  }
}

export class SetPerfFeePctCall__Inputs {
  _call: SetPerfFeePctCall;

  constructor(call: SetPerfFeePctCall) {
    this._call = call;
  }

  get _perfFeePct(): i32 {
    return this._call.inputValues[0].value.toI32();
  }
}

export class SetPerfFeePctCall__Outputs {
  _call: SetPerfFeePctCall;

  constructor(call: SetPerfFeePctCall) {
    this._call = call;
  }
}

export class SetStrategyCall extends ethereum.Call {
  get inputs(): SetStrategyCall__Inputs {
    return new SetStrategyCall__Inputs(this);
  }

  get outputs(): SetStrategyCall__Outputs {
    return new SetStrategyCall__Outputs(this);
  }
}

export class SetStrategyCall__Inputs {
  _call: SetStrategyCall;

  constructor(call: SetStrategyCall) {
    this._call = call;
  }

  get _strategy(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetStrategyCall__Outputs {
  _call: SetStrategyCall;

  constructor(call: SetStrategyCall) {
    this._call = call;
  }
}

export class SetTreasuryCall extends ethereum.Call {
  get inputs(): SetTreasuryCall__Inputs {
    return new SetTreasuryCall__Inputs(this);
  }

  get outputs(): SetTreasuryCall__Outputs {
    return new SetTreasuryCall__Outputs(this);
  }
}

export class SetTreasuryCall__Inputs {
  _call: SetTreasuryCall;

  constructor(call: SetTreasuryCall) {
    this._call = call;
  }

  get _treasury(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetTreasuryCall__Outputs {
  _call: SetTreasuryCall;

  constructor(call: SetTreasuryCall) {
    this._call = call;
  }
}
