name: Echidna Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - Echidna_Deposit_Withdraw

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: yarn install
    - run: yarn run hardhat compile

    - name: Cache ${{ matrix.test }} corpus
      uses: actions/cache@v2
      with:
        path: corpus
        key: abi-${{ matrix.test }}-v2

    - name: Run Echidna
      uses: crytic/echidna-action@v1
      with:
        solc-version: 0.8.10
        files: .
        contract: ${{ matrix.test }}
        crytic-args: --hardhat-ignore-compile
        config: contracts/echidna/${{ matrix.test }}.yml

    - name: Upload ${{ matrix.test }} coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.test }}
        path: corpus/covered.*