# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ALCHEMY_API_ENDPOINT: ${{ secrets.ALCHEMY_API_ENDPOINT }}
      CC_SECRET: ${{ secrets.CC_SECRET }}
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: yarn install
      - run: yarn run hardhat compile
      - run: NODE_ENV=test yarn run hardhat test
      - run: yarn codechecks
